baseURL = "https://disksing.com/"
languageCode = "zh-cn"
title = "硬盘在歌唱"
theme = "archie"
disqusShortname = "disksing"
googleAnalytics = "UA-154774927-1"
rssLimit = 20
hasCJKLanguage = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "colorful"
    tabWidth = 4

[params]
    author = "disksing"
    description = "我编程三日，两耳不闻人声，只有硬盘在歌唱。"
    profilePic = "profile.png"
    githubUsername = "disksing"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Noto Serif SC" # should match the name on Google Fonts!
    favicon = "favicon.png"

[permalinks]
    post = "/:filename"

[[menu.main]]
url = "/"
name = "主页"
weight = 1

[[menu.main]]
url = "/post/"
name = "文章"
weight = 2

# [[menu.main]]
# url = "/tip/"
# name = "知识点"
# weight = 3

# [[menu.main]]
# url = "/project/"
# name = "开源项目"
# weight = 4

# [[menu.main]]
# url = "/activity/"
# name = "动态"
# weight = 5

[[menu.main]]
url = "/about/"
name = "关于"
weight = 6

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/disksing/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/disksing/"

[[params.social]]
name = "Bilibili"
icon = "tv"
url = "https://space.bilibili.com/2207710"
