baseURL = "http://disksing.com/"
languageCode = "zh-cn"
title = "硬盘在歌唱"
theme = "minimal"
disqusShortname = ""
googleAnalytics = "UA-154774927-1"
rssLimit = 20

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "colorful"
    tabWidth = 4

[params]
    author = "disksing"
    description = "我编程三日，两耳不闻人声，只有硬盘在歌唱。"
    profilePic = "profile.png"
    githubUsername = "disksing"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    favicon = "favicon.png"

[permalinks]
    post = "/:filename"

[[menu.main]]
url = "/"
name = "主页"
weight = 1

[[menu.main]]
url = "/post/"
name = "文章"
weight = 2

[[menu.main]]
url = "/tip/"
name = "知识点"
weight = 3

[[menu.main]]
url = "/project/"
name = "开源项目"
weight = 4

[[menu.main]]
url = "/story/"
name = "故事"
weight = 5

[[menu.main]]
url = "/about/"
name = "关于"
weight = 6


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
url = "mailto:i@disksing.com"
name = "envelope-o"
weight = 1

[[menu.icon]]
url = "https://github.com/disksing/"
name = "github"
weight = 2

[[menu.icon]]
url = "http://weibo.com/539523448"
name = "weibo"
weight = 3

[[menu.icon]]
url = "http://shang.qq.com/wpa/qunwpa?idkey=ade2895067e4105ce59e0c56863d650543b4448245f179574c6684fe1cb7b5d5"
name = "qq"
weight = 4

[[menu.icon]]
url = "https://space.bilibili.com/2207710"
name = "tv"
weight = 5

[[menu.icon]]
url = "https://twitter.com/disksing/"
name = "twitter"
weight = 6

